name: Pipeline CNE

on:
  schedule:
    # al minuto 50 de cada hora
    - cron:  '59 23 * * 1'
  workflow_dispatch:

jobs:
  ejecutar_pipeline:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      CREDENTIALS_FILE: ${{ secrets.CREDENTIALS_FILE }}
      BUCKET_NAME: "archivos-pipeline-dta" # Define el nombre del bucket aquí
      SCRIPT_NAME: "main.py" # Define el nombre del script aquí

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests google-cloud-storage

      - name: Verificar variables de entorno
        run: |
          if [ -z "$EMAIL" ] || [ -z "$PASSWORD" ] || [ -z "$CREDENTIALS_FILE" ]; then
            echo "Error: Las variables de entorno EMAIL, PASSWORD o CREDENTIALS_FILE no están configuradas."
            exit 1
          fi

      - name: Ejecutar el script de Python
        run: python $SCRIPT_NAME

      - name: Imprimir mensaje de finalización
        run: echo "El pipeline de CNE se ha ejecutado exitosamente."        